### PR TITLE
Fix dropdowns on Account Settings-screen not working

### LINKED ISSUE #386: Impossible to change Default Listing Type and Default Sort Type on Account Settings-Screen

### PR DESCRIPTION
**Pull request by oscarnylander**
Fixes #386

### CODE REVIEW

File: app/src/main/java/com/jerboa/ui/components/common/InputFields.kt [hunk 1]
```diff
@@ -605,7 +606,9 @@ fun MyDropDown(
         TextField(
             readOnly = true,
             value = selectedText,
-            modifier = Modifier.fillMaxWidth(),
+            modifier = Modifier
+                .menuAnchor()
```
Comment (dessalines) [inline app/src/main/java/com/jerboa/ui/components/common/InputFields.kt:610]: Didn't know about this one, thx!

**Review by dessalines — APPROVED** [review]
