### PR TITLE
Fix thumbnail links being treated as images. Fixes #815

### LINKED ISSUE #815: Links are being treated as images
**Jerboa Version**

Main branch

**Describe the bug**

Clicking on a link tries to load an image, rather than going to the link.

**To Reproduce**

See above

**In the case of a crash**

### PR DESCRIPTION
**Pull request by dessalines**
Somewhere along the line, clicking on thumbnail links got removed, and every thumbnail was treated as an image, even if it was a link post.

This fixes that by altering the thumbnail tile to check to see if the url is an image.

### CODE REVIEW

File: app/src/main/java/com/jerboa/ui/components/post/PostListing.kt [hunk 1]
```diff
@@ -1095,9 +1141,23 @@ private fun ThumbnailTile(
...
+            .clickable {
+                if (isImage(url)) {
+                    showImageDialog = true
+                } else {
+                    openLink(
+                        url = url,
+                        navController = navController,
+                        useCustomTab = useCustomTabs,
+                        usePrivateTab = usePrivateTabs,
+                    )
```
Comment (dessalines) [inline app/src/main/java/com/jerboa/ui/components/post/PostListing.kt:1158]: Important code here.

**Review by beatgammit — APPROVED** [review]
Looks good to me.

I wonder if we can turn on a lint for variable mutability.
