### PR TITLE
Fix crash 0.37 due to missing SortTypes

### LINKED ISSUE #911: Jerboa crashing immediately after update to 0.0.37
**Jerboa Version**
0.0.37

**Android version + phone**
Android 13 (June 5th) on Pixel 6 Pro

**Describe the bug**
Jerboa crashes when opened. This only happened after the update from Play Store. Very briefly the "What's new" bubble is visible then the app completely crashes. 

**To Reproduce**
Open Jerboa

**In the case of a crash**

```
<details><summary>LOGS</summary>
--------- beginning of crash
06-29 13:57:28.269 13669 13669 E AndroidRuntime: FATAL EXCEPTION: main
06-29 13:57:28.269 13669 13669 E AndroidRuntime: Process: com.jerboa, PID: 13669
06-29 13:57:28.269 13669 13669 E AndroidRuntime: java.lang.NullPointerException: Parameter specified as non-null is null: method com.jerboa.ui.components.home.SiteViewModel$getSite$1.invokeSuspend, parameter sortType
06-29 13:57:28.269 13669 13669 E AndroidRuntime: 	at com.jerboa.ui.components.home.SiteViewModel$getSite$1.invokeSuspend(Unknown Source:111)
06-29 13:57:28.269 13669 13669 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
06-29 13:57:28.269 13669 13669 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:109)
06-29 13:57:28.269 13669 13669 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:942)
06-29 13:57:28.269 13669 13669 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
06-29 13:57:28.269 13669 13669 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
06-29 13:57:28.269 13669 13669 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
06-29 13:57:28.269 13669 13669 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7918)
06-29 13:57:28.269 13669 13669 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-29 13:57:28.269 13669 13669 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
06-29 13:57:28.269 13669 13669 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
06-29 13:57:28.269 13669 13669 E AndroidRuntime: 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@3da2935, Dispatchers.Main.immediate]
</details>
```

### PR DESCRIPTION
**Pull request by MV-GH**
Fixes the crash due to missing sortTypes, added the ones that were added in 0.18.
Refactor the sorttypes stuff, it was kept in different lists all over the place, kept centrally now. Had to look everywhere to find random bits of sortType logic. Yeah sorry twizmazin about not putting this in a seperate PR but i was  not going to write a bunch of duplicate code to remove it in the next pr.

When setting the value to TopThreeMonths or TopSixMonths or TopNineMonths. It causes a query error.  It does not cause a crash but no posts load in anymore until you change it. I believe this is actually rather a backend issue. Maybe months did get added a different version?
```
Query deserialize error: unknown variant `TopNineMonths`, expected one of `Active`, `Hot`, `New`, `Old`, `TopDay`, `TopWeek`, `TopMonth`, `TopYear`, `TopAll`, `MostComments`, `NewComments`, `TopHour`, `TopSixHour`, `TopTwelveHour`
```
Fixes #911

EDIT:

It seems these months ones weren't added yet. I have commented them for easy restoration for when they do get added. But that means they must be added again BEFORE they get released.

EDIT2:
I recommend actually keeping them as they get added in 18.1 and it causes no harm right now. It will only make it so that it will revert when set in the usersettings page. Or no posts will load in when set to one of these types

### CODE REVIEW

File: app/src/main/java/com/jerboa/ui/components/common/Dialogs.kt [hunk 1]
```diff
@@ -57,49 +60,26 @@ val DONATION_MARKDOWN = """
...
 """.trimIndent()
 
-val topSortTypes = listOf(
-    SortType.TopDay,
-    SortType.TopWeek,
-    SortType.TopMonth,
-    SortType.TopYear,
-    SortType.TopAll,
-)
+val topSortTypes = SortType.values().filter { it.name.startsWith("Top") }
```
Comment (dessalines) [inline app/src/main/java/com/jerboa/ui/components/common/Dialogs.kt:62]: I spose this is okay, although hard-coding them makes it much more clear.

**Review by dessalines — APPROVED** [review]
