### PR TITLE
Post actionbar design rework and options for it.

### LINKED ISSUE #639: Action Bar Buttons get pushed off screen when comment count is too high
** Jerboa Version **
0.0.34

**Describe the bug**
Action Bar Buttons beneath a post are being pushed off screen when the comment counter gets to high or has too much text  alltogether.

**To Reproduce**
1. Open Jerboa
2. Open one of the top comments with more then 100 comments
3. Check if the more action button is still visible
4. It is not (see screenshot)

Screenshot_20230614_130829_Jerboa (DEBUG)

I have a quick fix for this but its not a pretty one.

Screenshot_20230614_130853_Jerboa (DEBUG)

### PR DESCRIPTION
**Pull request by MV-GH**
Fixes #639

### CODE REVIEW

**Comment by MV-GH** [comment]
258817525-d46a72ea-0a15-49bc-8a44-802d55a0e207

To

(Only comment text changes)

258831200-418b565d-3ea8-49c7-87ad-ebd660c9a649

**Comment by MV-GH** [comment]
Rearrange footing + change icons

short form

258850794-9408a33a-0c50-4c98-b3f3-2b616122b83f

Long form, Im leaning for this rn

image

**Comment by MV-GH** [comment]
I'm thinking of making the post actionbar looks an option: (default long form), lefthand shortmode, righthand shortmode

**Comment by dessalines** [comment]
I like that a lot, IE the *+6* , with the badge, plus, and italics inline.

I'd def prefer the vote buttons stay on the right side, to the right of the comment icon and counts, at least until a left-handed mode is added.

Either comments icon looks good to me.

**Comment by MV-GH** [comment]
https://github.com/dessalines/jerboa/assets/67873169/dfc117b1-7724-4502-bd78-5e29da7adc89

Added the post actionbar mode settings. Do you still prefer comment to be to the left? @dessalines

**Comment by dessalines** [comment]
That looks good, except that the `short righthand` should probably still left-align the comment info. Most of this was taken from boost, which looks like this:

Screenshot_2023-08-07-15-16-30-700_com rubenmayayo reddit

If that's not doable tho, or would overly-complicate the code, it'd be fine to right-align everything tho.

**Comment by MV-GH** [comment]
image

Not that complex to implement. The lefthandside stays the same?
@dessalines

**Comment by dessalines** [comment]
Nice, that looks great!

Ya, the left-hand can stay the same.

**Comment by MV-GH** [comment]
Alright, I posted it in the community. We ll see feedback then this can be merged

File: app/src/main/java/com/jerboa/db/AppDBMigrations.kt [hunk 1]
```diff
@@ -321,4 +346,7 @@ val MIGRATIONS_LIST = arrayOf(
     MIGRATION_21_22,
     MIGRATION_22_21,
     MIGRATION_22_23,
+    MIGRATION_23_22,
+    MIGRATION_23_24,
+    MIGRATION_24_23,
```
Comment (dessalines) [inline app/src/main/java/com/jerboa/db/AppDBMigrations.kt:351]: I'm testing these now, but I've never done these down migrations in room. Aren't they going to undo the previous migration, or is that all taken care of by the database version?

File: app/src/main/java/com/jerboa/ui/components/settings/lookandfeel/LookAndFeelActivity.kt [hunk 2]
```diff
@@ -330,6 +334,23 @@ fun LookAndFeelActivity(
                         )
                     },
                 )
+                SettingsList(
+                    title = {
```
Comment (dessalines) [inline app/src/main/java/com/jerboa/ui/components/settings/lookandfeel/LookAndFeelActivity.kt:338]: I know its somewhat arbitrary, but I think the settings page looks *much* better when the types are grouped. Could you move the `Confirm exit` and `Post Actionbar Mode`, belowe the `Post View` setting, so that all the list-type settings are grouped above the boolean settings?

File: app/src/main/java/com/jerboa/db/AppDBMigrations.kt (hunk 1 above)
Comment (dessalines) [reply app/src/main/java/com/jerboa/db/AppDBMigrations.kt:351]: Edit: seems to be taken care of by DB version.

Comment (MV-GH) [reply app/src/main/java/com/jerboa/db/AppDBMigrations.kt:351]: They wont cause a downgrade, the version on instance is what causes which version we will be using, This list is just the path the migrator can use to change between versions. If there is no path then room db throws that error on startup that says no migration found. The order of this list doesn't even matter either. Just the version numbers. I just added them because it was trivial and you never know if we have a use case for them.

File: app/src/main/java/com/jerboa/ui/components/settings/lookandfeel/LookAndFeelActivity.kt (hunk 2 above)
Comment (MV-GH) [reply app/src/main/java/com/jerboa/ui/components/settings/lookandfeel/LookAndFeelActivity.kt:338]: I moved them

File: app/src/main/java/com/jerboa/feat/PostActionbarMode.kt [hunk 3]
```diff
@@ -0,0 +1,10 @@
+package com.jerboa.feat
+
+import androidx.annotation.StringRes
+import com.jerboa.R
+
+enum class PostActionbarMode(@StringRes val resId: Int) {
+    Long(R.string.post_actionbar_mode_long),
```
[the remark this answers is not in the document]
Comment (MV-GH) [reply app/src/main/java/com/jerboa/feat/PostActionbarMode.kt]: I preferred long tbh

I tweaked lefthand a bit not sure if its better or worse
afbeelding

File: app/src/main/java/com/jerboa/feat/PostActionbarMode.kt [hunk 4]
```diff
@@ -0,0 +1,10 @@
+package com.jerboa.feat
+
+import androidx.annotation.StringRes
+import com.jerboa.R
+
+enum class PostActionbarMode(@StringRes val resId: Int) {
+    LeftHandShort(R.string.post_actionbar_mode_short_left),
```
Comment (dessalines) [inline app/src/main/java/com/jerboa/feat/PostActionbarMode.kt:7]: It should be RightHandShort first.
