### PR TITLE
Fixing view votes crash. Fixes #1357

### LINKED ISSUE #1357: View votes crashes jerboa when there are multiple pages of votes
### Jerboa Version

main

### Android Version + Phone

any

### Describe The Bug

I get the `Conflicting Key` bug, implying that something is going wrong with the appending function

### To Reproduce

1. Click moderation -> view votes on any item
2. If its more than one page, jerboa crashes

### In the case of a crash or when relevant include the logs

See above

### PR DESCRIPTION
**Pull request by dessalines**

### CODE REVIEW

File: app/src/main/java/com/jerboa/model/CommentLikesViewModel.kt [hunk 1]
```diff
@@ -58,7 +60,11 @@ class CommentLikesViewModel(val id: CommentId) : ViewModel() {
             likesRes =
                 when (newRes) {
                     is ApiState.Success -> {
-                        val appended = appendData(oldRes.data.comment_likes, newRes.data.comment_likes)
+                        val appended =
+                            getDeduplicateMerge(
+                                oldRes.data.comment_likes,
+                                newRes.data.comment_likes,
+                            ) { it.creator.id }
```
Comment (MV-GH) [inline app/src/main/java/com/jerboa/model/CommentLikesViewModel.kt:67]: Is that unique per commentLike post?

**Review by MV-GH — APPROVED** [review]

File: app/src/main/java/com/jerboa/model/CommentLikesViewModel.kt (hunk 1 above)
Comment (dessalines) [reply app/src/main/java/com/jerboa/model/CommentLikesViewModel.kt:67]: Yep, user can only like an item once.
