### PR TITLE
Fixes missing comments causing `X more replies` to show instead the missing comments

### LINKED ISSUE #1183: Read more replies does not work, and pressing it too much will cause a crash
### Jerboa Version

0.0.44

### Android Version + Phone

N/A

### Describe The Bug

Press read more replies nothing happens, press it again nothing happens, start scrolling, crash

<details> 
<summary>stack trace </summary>
FATAL EXCEPTION: main
Process: com.jerboa, PID: 26802
java.lang.IllegalArgumentException: Key "1996313" was already used. If you are using LazyColumn/Row please make sure you provide a unique key for each item.
	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$Scope.subcompose(Unknown Source:182)
	at androidx.compose.foundation.lazy.layout.LazyLayoutMeasureScopeImpl.measure-0kLqBqw(Unknown Source:33)
	at androidx.compose.foundation.lazy.LazyListKt$rememberLazyListMeasurePolicy$1$1$measuredItemProvider$1.getAndMeasure(Unknown Source:18)
	at androidx.compose.foundation.lazy.LazyListKt$rememberLazyListMeasurePolicy$1$1.invoke(Unknown Source:617)
	at androidx.navigation.compose.NavHostKt$NavHost$14$1.invoke(SourceFile:16)
	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$createMeasurePolicy$1.measure-3p2s80s(Unknown Source:91)
	at androidx.compose.ui.node.InnerNodeCoordinator.measure-BRTryo0(Unknown Source:45)
	at androidx.compose.ui.graphics.SimpleGraphicsLayerModifier.measure-3p2s80s(Unknown Source:5)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(Unknown Source:10)
	at androidx.compose.foundation.layout.PaddingNode.measure-3p2s80s(Unknown Source:37)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(Unknown Source:10)
	at okhttp3.internal.http2.Http2Connection$1.invoke(SourceFile:17)
	at okhttp3.internal.http2.Http2Connection$1.invoke(SourceFile:13)
	at androidx.compose.ui.Alignment$Companion.observe(Unknown Source:63)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(Unknown Source:66)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(Unknown Source:75)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(Unknown Source:12)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.remeasure-BRTryo0(Unknown Source:109)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.doRemeasure-sdFAvZA(Unknown Source:17)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.measureAndLayout-0kLqBqw(Unknown Source:60)
	at androidx.compose.ui.platform.AndroidComposeView.measureAndLayout-0kLqBqw(Unknown Source:12)
	at androidx.compose.ui.node.LayoutNode.forceRemeasure(Unknown Source:40)
	at androidx.compose.foundation.MagnifierKt$magnifier$4$3.invoke(SourceFile:27)
	at androidx.compose.foundation.MagnifierKt$magnifier$4$3.invoke(SourceFile:105)
	at androidx.compose.foundation.gestures.DefaultScrollableState$scrollScope$1.scrollBy(Unknown Source:16)
	at androidx.compose.runtime.RecomposeScopeImpl$end$1$2.invoke(Unknown Source:357)
	at androidx.compose.foundation.AndroidEdgeEffectOverscrollEffect.applyToScroll-Rhakbz0(Unknown Source:327)
	at androidx.compose.foundation.gestures.ScrollingLogic.dispatchScroll-3eAAhYA(Unknown Source:49)
	at androidx.compose.ui.ZIndexNode$measure$1.invoke(SourceFile:144)
	at androidx.compose.foundation.gestures.ScrollingLogic$doFlingAnimation$2$scope$1.scrollBy(Unknown Source:13)
	at com.jerboa.UtilsKt$border$1.invoke(SourceFile:111)
	at com.jerboa.UtilsKt$border$1.invoke(SourceFile:47)
	at kotlin.TuplesKt.doAnimationFrameWithScale(Unknown Source:64)
	at androidx.compose.animation.core.SuspendAnimationKt$animate$9.invoke(Unknown Source:35)
	at androidx.compose.foundation.layout.OffsetKt$offset$2.invoke(SourceFile:37)
	at androidx.compose.runtime.BroadcastFrameClock.sendFrame(Unknown Source:33)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Unknown Source:33)
	at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(Unknown Source:6)
	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(Unknown Source:47)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1074)
	at android.view.Choreographer.doCallbacks(Choreographer.java:897)
	at android.view.Choreographer.doFrame(Choreographer.java:822)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1061)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8061)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@fa11508, androidx.compose.runtime.BroadcastFrameClock@82e94a1, StandaloneCoroutine{Cancelling}@2a486c6, AndroidUiDispatcher@441e687]

</details>

<details> 
<summary>json comments response </summary>

[issue_comments_reponse.zip](https://github.com/dessalines/jerboa/files/12359632/issue_comments_reponse.zip)

</details>

https://programming.dev/api/v3/comment/list?max_depth=6&parent_id=1992854&type_=All&auth=REDACTED
<details> 
<summary>json comments reply reponse </summary>

```json

{"comments":[{"comment":{"id":1992854,"creator_id":238618,"post_id":1758694,"content":" How's your linux phone doing?","removed":false,"published":"2023-08-16T03:34:30.515789","deleted":false,"ap_id":"https://sh.itjust.works/comment/2229734","local":false,"path":"0.1988963.1992854","distinguished":false,"language_id":37},"creator":{"id":238618,"name":"terath","banned":false,"published":"2023-06-16T16:33:27.044229","actor_id":"https://sh.itjust.works/u/terath","local":false,"deleted":false,"admin":false,"bot_account":false,"instance_id":38},"post":{"id":1758694,"name":"Today, Reddit forcibly removed me (and everyone else) as mods of /r/iOSProgramming, a subreddit of about 130k users. I was keeping the sub private / NSFW | Tanner B 🦕🧁 (@objc@mastodon.social)","url":"https://mastodon.social/@objc/110894496445183461","body":"Update:  !ios_dev@programming.dev has been created, temporarily managed by [@Ategon@programming.dev](https://programming.dev/u/Ategon)  until some mods volunteer for it","creator_id":144032,"community_id":3,"removed":false,"locked":false,"published":"2023-08-15T20:38:03.982406","updated":"2023-08-16T02:38:13.413296","deleted":false,"nsfw":false,"embed_title":"Tanner B 🦕🧁 (@objc@mastodon.social)","embed_description":"Today, Reddit forcibly removed me (and everyone else) as mods of /r/iOSProgramming, a subreddit of about 130k users. I was keeping the sub private / NSFW to prevent Reddit from monetizing it with ads.","ap_id":"https://programming.dev/post/1758694","local":true,"language_id":0,"featured_community":false,"featured_local":false},"community":{"id":3,"name":"programming","title":"Programming","description":"Welcome to the main community in programming.dev! Feel free to post anything relating to the instance here\n\nPeople will guide you in the replies to relevant communities for that kind of content to help get you communities in the instance to then join and make future posts in\n\nWe ask that if you do a help request please add [help] to the start of the post to help differentiate it from the rest of the posts until we get a flair system in\n\nHope you enjoy the instance!","removed":false,"published":"2023-06-06T06:54:33.621165","updated":"2023-07-19T01:58:48.287900","deleted":false,"nsfw":false,"actor_id":"https://programming.dev/c/programming","local":true,"icon":"https://programming.dev/pictrs/image/8140dda6-9512-4297-ac17-d303638c90a6.png","banner":"https://programming.dev/pictrs/image/d7711fb2-cb17-41cd-b06e-a6de83db25b7.jpeg","hidden":false,"posting_restricted_to_mods":false,"instance_id":1},"counts":{"id":1749956,"comment_id":1992854,"score":9,"upvotes":15,"downvotes":6,"published":"2023-08-16T03:34:30.515789","child_count":2,"hot_rank":145},"creator_banned_from_community":false,"subscribed":"NotSubscribed","saved":false,"creator_blocked":false},{"comment":{"id":1996313,"creator_id":1792187,"post_id":1758694,"content":"You know that all Apple devices are Unix too? You're not making a point and do not know what you're talking about.","removed":false,"published":"2023-08-16T06:33:28.203248","deleted":false,"ap_id":"https://feddit.nl/comment/1927381","local":false,"path":"0.1988963.1992854.1996159.1996313","distinguished":false,"language_id":0},"creator":{"id":1792187,"name":"kattenluik","banned":false,"published":"2023-08-05T00:22:43.051906","actor_id":"https://feddit.nl/u/kattenluik","local":false,"deleted":false,"admin":false,"bot_account":false,"instance_id":34},"post":{"id":1758694,"name":"Today, Reddit forcibly removed me (and everyone else) as mods of /r/iOSProgramming, a subreddit of about 130k users. I was keeping the sub private / NSFW | Tanner B 🦕🧁 (@objc@mastodon.social)","url":"https://mastodon.social/@objc/110894496445183461","body":"Update:  !ios_dev@programming.dev has been created, temporarily managed by [@Ategon@programming.dev](https://programming.dev/u/Ategon)  until some mods volunteer for it","creator_id":144032,"community_id":3,"removed":false,"locked":false,"published":"2023-08-15T20:38:03.982406","updated":"2023-08-16T02:38:13.413296","deleted":false,"nsfw":false,"embed_title":"Tanner B 🦕🧁 (@objc@mastodon.social)","embed_description":"Today, Reddit forcibly removed me (and everyone else) as mods of /r/iOSProgramming, a subreddit of about 130k users. I was keeping the sub private / NSFW to prevent Reddit from monetizing it with ads.","ap_id":"https://programming.dev/post/1758694","local":true,"language_id":0,"featured_community":false,"featured_local":false},"community":{"id":3,"name":"programming","title":"Programming","description":"Welcome to the main community in programming.dev! Feel free to post anything relating to the instance here\n\nPeople will guide you in the replies to relevant communities for that kind of content to help get you communities in the instance to then join and make future posts in\n\nWe ask that if you do a help request please add [help] to the start of the post to help differentiate it from the rest of the posts until we get a flair system in\n\nHope you enjoy the instance!","removed":false,"published":"2023-06-06T06:54:33.621165","updated":"2023-07-19T01:58:48.287900","deleted":false,"nsfw":false,"actor_id":"https://programming.dev/c/programming","local":true,"icon":"https://programming.dev/pictrs/image/8140dda6-9512-4297-ac17-d303638c90a6.png","banner":"https://programming.dev/pictrs/image/d7711fb2-cb17-41cd-b06e-a6de83db25b7.jpeg","hidden":false,"posting_restricted_to_mods":false,"instance_id":1},"counts":{"id":1752822,"comment_id":1996313,"score":2,"upvotes":4,"downvotes":2,"published":"2023-08-16T06:33:28.203248","child_count":0,"hot_rank":167},"creator_banned_from_community":false,"subscribed":"NotSubscribed","saved":false,"creator_blocked":false}]}

```

</details>

I dug into this, the read more replies correctly gets the right response

but the path is for the parent comment `0.1988963.1992854` and the child comment `0.1988963.1992854.1996159.1996313`

There is a comment missing there and Jerboa does not handle that properly

*Neither does Lemmy UI, tried to see what they did*

### To Reproduce

go to this post https://programming.dev/post/1758694
find the read more replies and press it

or alternative go directly to this comment
https://programming.dev/comment/1988963

### In the case of a crash or when relevant include the logs

<details> 
<summary>stack trace </summary>
FATAL EXCEPTION: main
Process: com.jerboa, PID: 26802
java.lang.IllegalArgumentException: Key "1996313" was already used. If you are using LazyColumn/Row please make sure you provide a unique key for each item.
	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$Scope.subcompose(Unknown Source:182)
	at androidx.compose.foundation.lazy.layout.LazyLayoutMeasureScopeImpl.measure-0kLqBqw(Unknown Source:33)
	at androidx.compose.foundation.lazy.LazyListKt$rememberLazyListMeasurePolicy$1$1$measuredItemProvider$1.getAndMeasure(Unknown Source:18)
	at androidx.compose.foundation.lazy.LazyListKt$rememberLazyListMeasurePolicy$1$1.invoke(Unknown Source:617)
	at androidx.navigation.compose.NavHostKt$NavHost$14$1.invoke(SourceFile:16)
	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$createMeasurePolicy$1.measure-3p2s80s(Unknown Source:91)
	at androidx.compose.ui.node.InnerNodeCoordinator.measure-BRTryo0(Unknown Source:45)
	at androidx.compose.ui.graphics.SimpleGraphicsLayerModifier.measure-3p2s80s(Unknown Source:5)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(Unknown Source:10)
	at androidx.compose.foundation.layout.PaddingNode.measure-3p2s80s(Unknown Source:37)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(Unknown Source:10)
	at okhttp3.internal.http2.Http2Connection$1.invoke(SourceFile:17)
	at okhttp3.internal.http2.Http2Connection$1.invoke(SourceFile:13)
	at androidx.compose.ui.Alignment$Companion.observe(Unknown Source:63)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(Unknown Source:66)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(Unknown Source:75)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(Unknown Source:12)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.remeasure-BRTryo0(Unknown Source:109)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.doRemeasure-sdFAvZA(Unknown Source:17)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.measureAndLayout-0kLqBqw(Unknown Source:60)
	at androidx.compose.ui.platform.AndroidComposeView.measureAndLayout-0kLqBqw(Unknown Source:12)
	at androidx.compose.ui.node.LayoutNode.forceRemeasure(Unknown Source:40)
	at androidx.compose.foundation.MagnifierKt$magnifier$4$3.invoke(SourceFile:27)
	at androidx.compose.foundation.MagnifierKt$magnifier$4$3.invoke(SourceFile:105)
	at androidx.compose.foundation.gestures.DefaultScrollableState$scrollScope$1.scrollBy(Unknown Source:16)
	at androidx.compose.runtime.RecomposeScopeImpl$end$1$2.invoke(Unknown Source:357)
	at androidx.compose.foundation.AndroidEdgeEffectOverscrollEffect.applyToScroll-Rhakbz0(Unknown Source:327)
	at androidx.compose.foundation.gestures.ScrollingLogic.dispatchScroll-3eAAhYA(Unknown Source:49)
	at androidx.compose.ui.ZIndexNode$measure$1.invoke(SourceFile:144)
	at androidx.compose.foundation.gestures.ScrollingLogic$doFlingAnimation$2$scope$1.scrollBy(Unknown Source:13)
	at com.jerboa.UtilsKt$border$1.invoke(SourceFile:111)
	at com.jerboa.UtilsKt$border$1.invoke(SourceFile:47)
	at kotlin.TuplesKt.doAnimationFrameWithScale(Unknown Source:64)
	at androidx.compose.animation.core.SuspendAnimationKt$animate$9.invoke(Unknown Source:35)
	at androidx.compose.foundation.layout.OffsetKt$offset$2.invoke(SourceFile:37)
	at androidx.compose.runtime.BroadcastFrameClock.sendFrame(Unknown Source:33)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Unknown Source:33)
	at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(Unknown Source:6)
	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(Unknown Source:47)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1074)
	at android.view.Choreographer.doCallbacks(Choreographer.java:897)
	at android.view.Choreographer.doFrame(Choreographer.java:822)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1061)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8061)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@fa11508, androidx.compose.runtime.BroadcastFrameClock@82e94a1, StandaloneCoroutine{Cancelling}@2a486c6, AndroidUiDispatcher@441e687]

</details>

### PR DESCRIPTION
**Pull request by MV-GH**
Before, the insertion of comments after a missing comment would go wrong. They would be inserted at the end of the tree

While the section that had the missing comments would have `X more replies` instead. Pressing this each time created more of those comments at the bottom of the tree. Once you scroll them into view it crashes as the tree can't have duplicate ids (we use the commentId as Id)

This ended up being far more complex than I thought it would be to fix. If there is a simpler way please let me know but this properly fixes it.

Fixes #1183

https://github.com/dessalines/jerboa/assets/67873169/61a1cd77-0368-4319-ae82-7e857ddfd96f

### CODE REVIEW

**Comment by dessalines** [comment]
This even changes the building tree logic, ugh. I have no idea why we aren't having this problem with lemmy-ui, as it uses the same code. This is one where the complication its adding its just not worth it.

> Because it is inserting twice the same comment because the read more replies button doesn't disappear

So then why don't we just hide / disable that more replies button after its been clicked once? 

Or just randomly generate an id?

**Comment by MV-GH** [comment]
LemmyUI does have a problem, it infinitely loads when this happens

Example:
go to this comment and click load more, infinitely loads there because the comment insertion logic is faulty (doesn't account for this edge case where a parent can be missing)
 https://programming.dev/comment/1988963


This change definitely needs to happen, The button isn't the problem. It adding the comments at the button because of the current logic because its missing comments. So its inserting it at the wrong nodes

```kt
 child?.let { cChild ->
            val parentId = getCommentParentId(cv.comment)
            parentId?.let { cParentId ->
                val parent = map[cParentId]

                // Necessary because blocked comment might not exist
                parent?.let { cParent ->
                    cParent.children?.add(cChild)
                }
            } ?: run {
                tree.add(cChild) // This is what makes it go wrong, comments which have missing parent, get added at end because of this
            }
        }
 ```

**Comment by MV-GH** [comment]
This problem, can be especially frequent (from what I heard) is when you start blocking users, as their comments won't be sent at all. Which can be in the middle of thread trees

**Comment by dessalines** [comment]
So maybe the `getCommentParentId` needs to also check the existing comments, to make sure that parent exists. Then it won't try to insert it. (Or it could toast an error).

[This PR](https://github.com/LemmyNet/lemmy/pull/3965) is related and should hopefully fix some of the issues with missing branches (at least when the comment is deleted or removed), but not all (at least with user blocks). 

IMO this case should be handled in a much simpler way, but just checking to make sure the parent exists first.

**Comment by MV-GH** [comment]
I am not entirely following with the `getCommentParentId` changes, This util function just returns the id of the parent by checking the path and getting the one before the last.

That PR only solves one fraction of the problem. Not the problem that LemmyUI can't navigate nor correctly construct trees with missing comments in between them. (Neither can Jerboa but this solves that) 

> IMO this case should be handled in a much simpler way, but just checking to make sure the parent exists first.

We do that already and we insert them at the end. If there is no parent. But this causes different "trees" to mashup together look like they are part of the last comment tree but they aren't and also causes a crash for Jerboa because it cant handle duplicate comments

**Comment by dessalines** [comment]
> This util function just returns the id of the parent by checking the path and getting the one before the last.

I'm recommending that we not just check the string, but also make sure the parent *exists* in the comment node list. The root cause of this issue is that its trying to construct a tree branch with a missing parent, which is impossible.

**Comment by dessalines** [comment]
See [this issue](https://github.com/LemmyNet/lemmy/pull/3965) , and what I propose the best way to solve it is: to not have any missing comments in trees, and use properties like `deleted`, `removed`, `creator_blocked` on the `CommentView` to render them correctly.

Faking missing comments isn't a good long-term solution for this problem, and its one that all the front ends are going to have to deal with, and they shouldn't have to deal with adding these super-complicated hacks for missing comments.

Also I haven't tested this, but there could be multiple levels of missing comments, not just a single level, which means you'd need to recursively fake them.

**Comment by MV-GH** [comment]
> See https://github.com/LemmyNet/lemmy/pull/3965 , and what I propose the best way to solve it is: to not have any missing comments in trees, and use properties like deleted, removed, creator_blocked on the CommentView to render them correctly, but still have the full tree available.

I'll respond there too, I do prefer this as we can show reasons for hidden comments (and more info that is missing now)

> Also I haven't tested this, but there could be multiple levels of missing comments, not just a single level, which means you'd need to recursively fake them.

Yes that is correct, it can even have a missing top comments. And this solution/PR solves this too. See `recCreateAndGenMissingCommentData` Which recursively walks through the tree on insertion of a comment with a missing parent. To recreate the missing comment (and its potential missing parent, ...)

> Faking missing comments isn't a good long-term solution for this problem, and its one that all the front ends are going to have to deal with, and they shouldn't have to deal with adding these super-complicated hacks for missing comments.

I do not consider this a "hack". It does increase the complexity of the tree creation logic, but most of the complexity is dealing with the types. I could avoid this by creating "fake" commentViews (instead of Either<MissingCommentNode, CommentVIew>) but I didn't want to do this as it feels more "hacky".

And yes, indeed a problem all clients will have to deal with. (And I assume some already do, as I have not heard of any problems yet)

It is naive to assume that the server will always return complete trees. During the CSAM problematic period, admins were deleting comments straight from within the DB. How would the server solve these problems?

**Comment by MV-GH** [comment]
I think, i could change the Either<Missing, CommentView> to  A sealed type if that is preferred. Would probably bring down type complexity a bit.

If it puts you more at ease I can write unit tests, to insure that the new comment tree creation logic works as intended.

**Review by dessalines — COMMENTED** [review]
I could go line by line to try to decipher what these 3+ functions you've added are doing and how they fit together, because I can barely follow it. Several of them doing *more* loops than the two that are used to build a simple tree, which comes from simple tree-building pseudo-code that's proven reliable.

My order of preference from best to worst would be : 

- Fix this issue on the back end.
- Don't build tree branches for missing comments, just ignore it.
- Make complicated tree logic for faking non-existing tree nodes like you've done here.

This is a very dangerous PR to merge IMO. At the very least please add a TODO with this PR link / commit so we can remove it when the back-end code is fixed.

File: app/src/main/java/com/jerboa/Utils.kt [hunk 1]
```diff
@@ -238,64 +239,135 @@ data class InstantScores(
...
+
     val map = LinkedHashMap<Number, CommentNodeData>()
     val firstComment = comments.firstOrNull()?.comment
 
-    val depthOffset = if (!isCommentView) {
-        0
+    val depthOffset = if (isCommentView && firstComment != null) {
+        getCommentIdDepthFromPath(firstComment.path, rootCommentId!!)
     } else {
-        getDepthFromComment(firstComment) ?: 0
```
Comment (MV-GH) [inline app/src/main/java/com/jerboa/Utils.kt:264]: This logic was wrong and caused the depth of the commentTree to be reversed.

Because this incorrectly assumes that the first comment has the lowest depth. (This is not always case such as when you use the parent_id due to a bug in 0.18.3) Thus causing the list to be generated with negative depth, This doesn't a problem (by sheer luck?) because the color handles this negative depth because it uses modulo and the calculateCommentOffset handles this correctly because it uses abs.

It does it correctly now because it gets the depth of the root comment. (which is always the lowest)

see https://lemmy.one/api/v3/comment/list?max_depth=6&parent_id=3355587&sort=Hot&type_=All&auth=REDACTED

Before
image

After:
image

**Comment by MV-GH** [comment]
@dessalines I have removed one of the complex methods. Added more comments to the recursive one added tests for the buildCommentTree, simplified the generic commentNodeData holder to a Sealed type

I do believe this change is absolutely necessary. It can be removed once we no longer support a version of Lemmy that has this problem. But this won't be fixed 0.19. And when I ask users for their crash logs. This is the only crash that shows up. And it is very frequent (occurring daily).

**Review by dessalines — APPROVED** [review]
Very well. I'd thought lemmy v0.19 had this fixed tho. If it doesn't that needs to be addressed, because this affects all UIs.
