### PR TITLE
Fixing community pages, used wrong ID_TYPE. Fixes #1348

### LINKED ISSUE #1348: All community pages are broken in `0.0.56`
### Jerboa Version

0.0.56

### Android Version + Phone

all

### Describe The Bug

Every community page displays "Couldn't find community". 

### To Reproduce

1. Click on any community page
2. It displays the error above

### In the case of a crash or when relevant include the logs

NA

### PR DESCRIPTION
**Pull request by dessalines**

### CODE REVIEW

File: app/src/main/java/com/jerboa/ui/components/common/Route.kt [hunk 1]
```diff
@@ -62,7 +62,7 @@ object Route {
 
         companion object {
             const val ID = "id"
-            val ID_TYPE = NavType.IntType
+            val ID_TYPE = NavType.LongType
```
Comment (dessalines) [inline app/src/main/java/com/jerboa/ui/components/common/Route.kt:65]: Dang compiler not finding this one

**Review by MV-GH — APPROVED** [review]

File: app/src/main/java/com/jerboa/ui/components/common/Route.kt (hunk 1 above)
Comment (MV-GH) [reply app/src/main/java/com/jerboa/ui/components/common/Route.kt:65]: Yeah it sucks we cant do this type safe

Comment (dessalines) [reply app/src/main/java/com/jerboa/ui/components/common/Route.kt:65]: Oh well. I'll get another release out tmrw with these two fixes.
